obj-$(CONFIG_SOFTMMU) += monitor.o
obj-y += translate.o fp_helper.o op_helper.o helper.o cpu.o
obj-y += gdbstub.o
obj-y += xtensa-semi.o
obj-y += core-dc232b.o
obj-y += core-dc233c.o
obj-y += core-fsf.o
obj-y += core-fsf_2014.o
